import { createContext, useState } from 'react';

const translations = {
  es: {
    "nav.about": "Sobre mí",
    "nav.skills": "Skills",
    "nav.projects": "Proyectos",
    "nav.courses": "Formación",
    "nav.contact": "Contacto",
    "hero.greeting.morning": "Buenos Días",
    "hero.greeting.afternoon": "Buenas Tardes",
    "hero.greeting.evening": "Buenas Noches",
    "hero.yosoy": "Yo Soy",
    "hero.marquee": "INGENIERÍA INFORMÁTICA  ✦  CIBERSEGURIDAD  ✦  CIENCIA DE DATOS  ✦  DESARROLLO WEB  ✦  INTELIGENCIA ARTIFICIAL  ✦  ",
    "hero.bio.label": "Sobre mi perfil",
    "hero.bio.text": "Soy <span>estudiante de ingeniería informática</span> con especialidad en Ciencia de datos.",
    "hero.bio.sub": "Enfocada en ciberseguridad, desarrollo móvil, desarrollo Web.",
    "hero.cv": "Descargar CV",
    "hero.available": "Disponible ahora",
    "about.capsule": "Sobre mi",
    "about.location.label": "Mi residencia",
    "about.location.text": "Guadalupe Victoria<br/>Durango, México",
    "about.subtitle": "Ingeniería Informática | Inteligencia de Mercados & Data Science",
    "about.education": "Educación",
    "about.institution": "Instituto Tecnológico Superior de la región de los llanos",
    "about.period": "2022-2027",
    "about.languages": "Competencia Lingüística",
    "about.lang.spanish": "Español",
    "about.lang.native": "(Nativo)",
    "about.lang.english": "Inglés",
    "about.lang.b1": "(Nivel B1)",
    "about.lang.korean": "Coreano",
    "about.lang.topik": "(TOPIK 2)",
    "skills.title": "Habilidades <span>Técnicas</span>",
    "skills.subtitle": "Stack Tecnológico y Especialidades",
    "skills.capsule": "Skills",
    "skills.cat.web": "Desarrollo Web",
    "skills.cat.mobile": "Desarrollo Móvil",
    "skills.cat.programming": "Programación",
    "skills.cat.iot": "IoT",
    "skills.cat.databases": "Bases de datos",
    "skills.cat.tools": "Herramientas",
    "courses.title": "Línea de <span>Formación</span>",
    "courses.subtitle": "Certificaciones y Especializaciones",
    "courses.capsule": "Formación",
    "courses.1.title": "Desarrollo con IA: de 0 a Producción",
    "courses.1.desc": "Jornadas formativas para la integración y despliegue de Inteligencia Artificial en entornos de producción.",
    "courses.1.institution": "BIG School",
    "courses.1.date": "14 de Abril, 2026",
    "courses.1.duration": "6 horas",
    "courses.2.title": "Ciberseguridad y Hacking Ético",
    "courses.2.desc": "Técnicas de detección de vulnerabilidades y defensa digital aplicadas a la ciberseguridad.",
    "courses.2.institution": "BIG School",
    "courses.2.date": "13 de Abril, 2026",
    "courses.2.duration": "6 horas",
    "courses.3.title": "Diseño Web con IA y FIGMA",
    "courses.3.desc": "Diseño Web: La estética conecta, de la idea visual a la experiencia digital en Figma.",
    "courses.3.institution": "ITSRLL",
    "courses.3.date": "Octubre, 2025",
    "courses.3.duration": "15 horas",
    "courses.4.title": "Desarrollo Frontend en HTML",
    "courses.4.desc": "Desarrollo y estructuración de páginas completas en HTML.",
    "courses.4.institution": "ITSRLL",
    "courses.4.date": "Octubre, 2023",
    "courses.4.duration": "15 horas",
    "courses.5.title": "Introducción a la Ciberseguridad",
    "courses.5.desc": "Introducción a los conceptos de ciberseguridad.",
    "courses.5.institution": "Cisco Networking Academy",
    "courses.5.date": "Mayo, 2026",
    "courses.5.duration": "6 horas",
    "projects.capsule": "Proyectos Destacados",
    "projects.subtitle": "Desarrollo, Innovación e Ingeniería",
    "projects.noimage": "Sin imagen",
    "projects.stack": "Stack Técnico",
    "projects.softskills": "Habilidades Blandas",
    "projects.repo": "Ver Repositorio",
    "projects.demo": "Ver Demo en Vivo",
    "projects.1.title": "OnFire!V1",
    "projects.1.desc": "Sistema IoT para detección de incendios forestales usando ESP32 y usando API REST para obtener datos del clima y la mejor ruta para llegar al incendio.",
    "projects.1.skill1": "Resolución de Problemas",
    "projects.1.skill2": "Innovación",
    "projects.1.skill3": "Gestión de Proyectos",
    "projects.1.skill4": "Trabajo en Equipo",
    "projects.1.skill5": "Liderazgo",
    "projects.2.title": "Drum Pad",
    "projects.2.desc": "Aplicación web interactiva para crear ritmos y experimentar con sonidos percusivos. Permite componer secuencias rítmicas tocando samples en tiempo real.",
    "projects.2.skill1": "Resolución de Problemas",
    "projects.2.skill2": "Creatividad",
    "projects.2.skill3": "Adaptabilidad",
    "projects.3.title": "MusicIA",
    "projects.3.desc": "Plataforma que permite a los usuarios crear piezas musicales únicas y originales mediante IA y MIDI.",
    "projects.3.skill1": "Innovación",
    "projects.3.skill2": "Creatividad",
    "projects.3.skill3": "Adaptabilidad",
    "projects.4.title": "Deredo",
    "projects.4.desc": "Aplicación movil de turismo, consumo local y venta local en Durango con una interfaz amable y fácil de usar, que permite a los usuarios descubrir lugares turísticos, restaurantes, tiendas y centros turísticos naturales en Durango, fomentando el turismo y el consumo local.",
    "projects.4.skill1": "Innovación",
    "projects.4.skill2": "Creatividad",
    "projects.4.skill3": "Adaptabilidad",
    "projects.4.skill4": "Trabajo en equipo",
    "projects.4.skill5": "Resolución de problemas",
    "projects.1.problem": "Los incendios forestales suelen detectarse demasiado tarde, provocando daños masivos y poniendo en riesgo vidas humanas. Además, la falta de datos climáticos en tiempo real dificulta la contención.",
    "projects.1.solution": "Se desarrolló un sistema IoT autónomo con ESP32 que monitorea variables ambientales en tiempo real, alertando de forma temprana. Se integró una API REST para calcular la ruta más rápida y segura para los equipos de emergencia.",
    "projects.2.problem": "Muchos creadores de música y aficionados carecen de herramientas accesibles e interactivas en línea para esbozar ritmos rápidos sin necesidad de instalar software complejo o pesado.",
    "projects.2.solution": "Se construyó una interfaz intuitiva que mapea teclas a samples percusivos, optimizando la latencia de audio para permitir una experiencia de creación rítmica fluida y en tiempo real directamente en la web.",
    "projects.3.problem": "La composición musical desde cero puede ser intimidante y requiere un alto nivel de conocimientos de teoría musical, lo que limita a muchas personas creativas sin formación formal.",
    "projects.3.solution": "Se implementó un modelo de inteligencia artificial capaz de generar secuencias MIDI basándose en parámetros seleccionados por el usuario, democratizando la creación musical y sirviendo como herramienta de inspiración.",
    "projects.4.problem": "Los turistas y locales de Durango a menudo desconocen los negocios locales y atractivos turísticos ocultos debido a la falta de una plataforma centralizada y fácil de usar para descubrirlos.",
    "projects.4.solution": "Se diseñó y desarrolló una aplicación móvil con Flutter que centraliza puntos de interés y negocios locales. Se utilizó IA para recomendar rutas personalizadas, fomentando directamente el turismo y la economía local.",
    "projects.4.badge": "🏆 Proyecto Ganador del Hackatón Hack Days Durango",
    "contact.capsule": "Contacto",
    "contact.heading": "¿Tienes una idea?",
    "contact.cta": "Hagámosla realidad",
    "contact.available": "Disponible para colaborar en proyectos de <span>ingeniería</span> y <span>datos</span>",
    "footer.credit": "Diseñado y desarrollado por",
  },
  en: {
    "nav.about": "About me",
    "nav.skills": "Skills",
    "nav.projects": "Projects",
    "nav.courses": "Education",
    "nav.contact": "Contact",
    "hero.greeting.morning": "Good Morning",
    "hero.greeting.afternoon": "Good Afternoon",
    "hero.greeting.evening": "Good Evening",
    "hero.yosoy": "I am",
    "hero.marquee": "COMPUTER ENGINEERING  ✦  CYBERSECURITY  ✦  DATA SCIENCE  ✦  WEB DEVELOPMENT  ✦  ARTIFICIAL INTELLIGENCE  ✦  ",
    "hero.bio.label": "About my profile",
    "hero.bio.text": "I am a <span>computer engineering student</span> specialized in Data Science.",
    "hero.bio.sub": "Focused on cybersecurity, mobile development, and Web development.",
    "hero.cv": "Download CV",
    "hero.available": "Available now",
    "about.capsule": "About me",
    "about.location.label": "Location",
    "about.location.text": "Guadalupe Victoria<br/>Durango, Mexico",
    "about.subtitle": "Computer Engineering | Market Intelligence & Data Science",
    "about.education": "Education",
    "about.institution": "Higher Technological Institute of the Llanos Region",
    "about.period": "2022-2027",
    "about.languages": "Languages",
    "about.lang.spanish": "Spanish",
    "about.lang.native": "(Native)",
    "about.lang.english": "English",
    "about.lang.b1": "(B1 Level)",
    "about.lang.korean": "Korean",
    "about.lang.topik": "(TOPIK 2)",
    "skills.title": "Technical <span>Skills</span>",
    "skills.subtitle": "Tech Stack & Specialties",
    "skills.capsule": "Skills",
    "skills.cat.web": "Web Development",
    "skills.cat.mobile": "Mobile Development",
    "skills.cat.programming": "Programming",
    "skills.cat.iot": "IoT",
    "skills.cat.databases": "Databases",
    "skills.cat.tools": "Tools",
    "courses.title": "Education <span>Path</span>",
    "courses.subtitle": "Certifications & Specializations",
    "courses.capsule": "Education",
    "courses.1.title": "AI Development: from 0 to Production",
    "courses.1.desc": "Training sessions for integrating and deploying Artificial Intelligence in production environments.",
    "courses.1.institution": "BIG School",
    "courses.1.date": "April 14, 2026",
    "courses.1.duration": "6 hours",
    "courses.2.title": "Cybersecurity and Ethical Hacking",
    "courses.2.desc": "Vulnerability detection techniques and digital defense applied to cybersecurity.",
    "courses.2.institution": "BIG School",
    "courses.2.date": "April 13, 2026",
    "courses.2.duration": "6 hours",
    "courses.3.title": "Web Design with AI and FIGMA",
    "courses.3.desc": "Web Design: Aesthetics connect, from visual idea to digital experience in Figma.",
    "courses.3.institution": "ITSRLL",
    "courses.3.date": "October, 2025",
    "courses.3.duration": "15 hours",
    "courses.4.title": "Frontend Development in HTML",
    "courses.4.desc": "Development and structuring of complete pages in HTML.",
    "courses.4.institution": "ITSRLL",
    "courses.4.date": "October, 2023",
    "courses.4.duration": "15 hours",
    "courses.5.title": "Introduction to Cybersecurity",
    "courses.5.desc": "Introduction to cybersecurity concepts.",
    "courses.5.institution": "Cisco Networking Academy",
    "courses.5.date": "May, 2026",
    "courses.5.duration": "6 hours",
    "projects.capsule": "Featured Projects",
    "projects.subtitle": "Development, Innovation & Engineering",
    "projects.noimage": "No image",
    "projects.stack": "Tech Stack",
    "projects.softskills": "Soft Skills",
    "projects.repo": "View Repository",
    "projects.demo": "View Live Demo",
    "projects.1.title": "OnFire!V1",
    "projects.1.desc": "IoT system for detecting forest fires using ESP32 and a REST API to obtain weather data and the best route to the fire.",
    "projects.1.skill1": "Problem Solving",
    "projects.1.skill2": "Innovation",
    "projects.1.skill3": "Project Management",
    "projects.1.skill4": "Teamwork",
    "projects.1.skill5": "Leadership",
    "projects.2.title": "Drum Pad",
    "projects.2.desc": "Interactive web application to create rhythms and experiment with percussive sounds. Allows composing rhythmic sequences by playing samples in real time.",
    "projects.2.skill1": "Problem Solving",
    "projects.2.skill2": "Creativity",
    "projects.2.skill3": "Adaptability",
    "projects.3.title": "MusicIA",
    "projects.3.desc": "Platform that allows users to create unique and original musical pieces using AI and MIDI.",
    "projects.3.skill1": "Innovation",
    "projects.3.skill2": "Creativity",
    "projects.3.skill3": "Adaptability",
    "projects.4.title": "Deredo",
    "projects.4.desc": "Mobile tourism, local consumption, and local sales app in Durango with a friendly and easy-to-use interface, allowing users to discover tourist spots, restaurants, stores, and natural tourist centers in Durango, promoting tourism and local consumption.",
    "projects.4.skill1": "Innovation",
    "projects.4.skill2": "Creativity",
    "projects.4.skill3": "Adaptability",
    "projects.4.skill4": "Teamwork",
    "projects.4.skill5": "Problem Solving",
    "projects.1.problem": "Forest fires are often detected too late, causing massive damage and putting human lives at risk. In addition, the lack of real-time weather data hinders containment efforts.",
    "projects.1.solution": "An autonomous IoT system with ESP32 was developed to monitor environmental variables in real-time, providing early warnings. A REST API was integrated to calculate the fastest and safest route for emergency teams.",
    "projects.2.problem": "Many music creators and enthusiasts lack accessible, interactive online tools to sketch quick beats without installing complex or heavy software.",
    "projects.2.solution": "An intuitive interface was built that maps keys to percussive samples, optimizing audio latency to allow a fluid, real-time rhythm creation experience directly on the web.",
    "projects.3.problem": "Composing music from scratch can be intimidating and requires a high level of music theory knowledge, limiting many creative individuals without formal training.",
    "projects.3.solution": "An artificial intelligence model capable of generating MIDI sequences based on user-selected parameters was implemented, democratizing music creation and serving as an inspiration tool.",
    "projects.4.problem": "Tourists and locals in Durango are often unaware of local businesses and hidden tourist attractions due to the lack of a centralized, easy-to-use platform to discover them.",
    "projects.4.solution": "A mobile application was designed and developed with Flutter that centralizes points of interest and local businesses. AI was used to recommend personalized routes, directly promoting tourism and the local economy.",
    "projects.4.badge": "🏆 Winning Project of the Hack Days Durango Hackathon",
    "contact.capsule": "Contact",
    "contact.heading": "Got an idea?",
    "contact.cta": "Let's make it happen",
    "contact.available": "Available to collaborate on <span>engineering</span> and <span>data</span> projects",
    "footer.credit": "Designed and developed by",
  }
};

export const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'es');

  const toggleLanguage = () => {
    setLanguage(prev => {
      const next = prev === 'es' ? 'en' : 'es';
      localStorage.setItem('language', next);
      return next;
    });
  };

  const t = (key) => translations[language]?.[key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
